language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php ./composer.phar install --dev --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml.dist
  - ./vendor/bin/phpcs --standard=PSR2 src/